require './_config'
require 'securerandom'

client = Cubepay::Client.new(CLIENT_ID, CLIENT_SECRET, URL);

# Coin id of your original list price (447 means USD).
source_coin_id = 447
# Original list price of your product price (100 USD).
source_amount = 100
# The customize name of your item.
item_name = "Test Item Name"
# Transaction ID generated by your shop (Recommend be unique).
merchant_transaction_id = SecureRandom.uuid
# Other information you can pass to the payment, such as your member id, your product id or anything you want,
# We'll return the field for your at IPN_URL.
other = "member_account=peter||product_id=product_test"
# The url you want your customer back to. it will show a link button on the coin pay page.
return_url = ""
# When the payment finish(success), we'll sending transaction information as your request parameter by POST method.
ipn_url = ""
# Coin id you want to send back to your customer, we'll send this coin to receive_address you define.
# If you pass value on send_coin_id, you should pass value on receive_address and send_amount too.
send_coin_id = ""
# Coin amount you want to send back to your customer.
# Must be positive number and large then zero, and make sure you have enough amount of the send coin.
send_amount = ""
# Coin address you want to send back to your customer.
receive_address = ""

# Coin id you want receive. (1 means ETH).
coin_id = 1

result = client.do_payment_by_coin_id(coin_id, source_coin_id, source_amount, item_name, merchant_transaction_id, other,
                                      return_url, ipn_url, send_coin_id, send_amount, receive_address)
print result
